### PR TITLE
React Calculator App - Milestone 4

### PR DESCRIPTION
**Pull request by 300ms**
- Implement logic module "calculate.js"
- Implement logic module "operate.js"

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [x] `calculate.js` should be imported in `App component`. (As you didn't commit the App.js file in this branch, as a result, I was not able to add inline comments)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

-

**Review by whiz25 — CHANGES_REQUESTED** [review]
## changes required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested change. You did well.

### changes 🔕 🔕 🔕 
- fix linter errors

### Martin Afani
#### Slack: whiz25

**Comment by 300ms** [comment]
>   `calculate.js` should be imported in `App component`. (As you didn't commit the App.js file in this branch, as a result, I was not able to add inline comments)

I've imported the calculate module into App component, but now i have an error;
"'Calculate' is defined but never used  no-unused-vars"

That was why I did not import it at the first time. Not it is imported.

**Comment by 300ms** [comment]
@whiz25 

> > `calculate.js` should be imported in `App component`. (As you didn't commit the App.js file in this branch, as a result, I was not able to add inline comments)
> 
> I've imported the calculate module into App component, but now i have an error;
> "'Calculate' is defined but never used no-unused-vars"
> 
> That was why I did not import it at the first time. Not it is imported.

**Review by george-shammar — APPROVED** [review]
Hi @300ms , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
